### ISSUE TITLE
Feature Request: 0 size for children

### ISSUE THREAD

**Issue by 0xNF** [caduandrade/multi_split_view#21]
I have a usecase where'd I'd like to stack all the children together as close to their dividers as possible. At the moment minimum size of 0 means "ignore", but I'd like it if it really did mean "0".

**Comment by caduandrade** [comment]
Initially, I worried about the side effect of not being able to increase the size of the child anymore when the divider is too small in width. This would only happen because it would be difficult to click on the correct divider. This is even worse given that your other suggestion (#22) has not yet been implemented. On the other hand, decreasing the width of the divider is the developer's decision. I will take a look.

**Comment by caduandrade** [comment]
Resolved by #24

**Comment by 0xNF** [comment]
I'm just checking this out now but I want to say that it works well and is quite nice -- thank you!
