### ISSUE TITLE
How to keep the width of a view when the window size changes?

### ISSUE THREAD

**Issue by ngugcx** [caduandrade/multi_split_view#33]
```
MultiSplitViewController(areas: [Area(size: 300)]);
```
I set width of the first view to size of 300, but it changes when the window is maximized.
How can I get it fixed?

**Comment by caduandrade** [comment]
Hi @ngugcx !

The widget is based on weights. The `size` parameter sets the initial weight but does not keep the size fixed in pixels. If the widget were in pixels, the problem would be worse when maximizing.

Maybe I should rename `size` to `initialSize`.

I believe that later there could be a parameter to keep the weight and even size in pixels fixed as well. But I would have to think about what some behaviors would be like. Example: How to fill the space if all areas have a fixed size in pixels but the sum of all areas is smaller than the available space?

For now, I believe you can use a `LayoutBuilder` to detect your window size change. Every time the size changes, you could change the size of the area. Would have to check if the user has already resized too. If you want to keep the width fixed, maybe you should handle the layout outside of `MultiSplitView`.

**Comment by caduandrade** [comment]
Will be resolved by #54

**Comment by caduandrade** [comment]
Better late than never (version 3.0.0) 😬
