### ISSUE TITLE
After the window is resized, the Area disappears

### ISSUE THREAD

**Issue by feimenggo** [caduandrade/multi_split_view#61]
After the window is resized, the Area disappears.

https://github.com/caduandrade/multi_split_view/assets/12608693/0e88320c-e55d-4982-9cd4-6edd38768634

**Comment by caduandrade** [comment]
Hi @feimenggo !

Ignoring the minimum, the area is expected to disappear once there is no more space. Once it has shrunk, it does not recover because the size value has already changed in the area.

But in this case, I understand that I could recover the minimum size. I didn't even consider this case.

Perhaps you could have a policy similar to `SizeUnderflowPolicy` ( stretchFirst, stretchLast, stretchAll ) to define the order of areas that must have a minimum area size recovered.

**Comment by caduandrade** [comment]
Hi @feimenggo !

Done. Version 3.0.1

Tks!
